# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/strategy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/strategy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/strategy.proto\x12\x08strategy\"\x94\x01\n\x08TickData\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x36\n\nindicators\x18\x03 \x03(\x0b\x32\".strategy.TickData.IndicatorsEntry\x1a\x31\n\x0fIndicatorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"D\n\x06Signal\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x01\x12\x0c\n\x04note\x18\x04 \x01(\t2C\n\x0fStrategyService\x12\x30\n\x06OnTick\x12\x12.strategy.TickData\x1a\x10.strategy.Signal\"\x00\x42\x14Z\x12trading-core/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.strategy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022trading-core/proto'
  _globals['_TICKDATA_INDICATORSENTRY']._loaded_options = None
  _globals['_TICKDATA_INDICATORSENTRY']._serialized_options = b'8\001'
  _globals['_TICKDATA']._serialized_start=35
  _globals['_TICKDATA']._serialized_end=183
  _globals['_TICKDATA_INDICATORSENTRY']._serialized_start=134
  _globals['_TICKDATA_INDICATORSENTRY']._serialized_end=183
  _globals['_SIGNAL']._serialized_start=185
  _globals['_SIGNAL']._serialized_end=253
  _globals['_STRATEGYSERVICE']._serialized_start=255
  _globals['_STRATEGYSERVICE']._serialized_end=322
# @@protoc_insertion_point(module_scope)
